In [23]:
pd.set_option ('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [28]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# -----------------------------------
# Supabase owner/admin connection
# -----------------------------------
host = "db.ogkdfmkybqtrsglcizzt.supabase.co"   # direct host
port = 5432
database = "postgres"
user = "postgres"
password = quote_plus("Bonabosssfs01")   # replace with your real password

engine = create_engine(
    f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}?sslmode=require",
    pool_pre_ping=True
)

# -----------------------------------
# Example extraction
# -----------------------------------
df_sales = pd.read_sql("""
SELECT *
FROM core.fact_sales
ORDER BY date ASC
""", engine)

In [29]:
import pandas as pd

# -------------------------
# DIM TABLES
# -------------------------

df_calendar = pd.read_sql("""
SELECT * FROM core.dim_calendar
ORDER BY date ASC
""", engine)

df_policy_regimes = pd.read_sql("""
SELECT * FROM core.dim_policy_regimes
ORDER BY start_date ASC
""", engine)

df_products = pd.read_sql("""
SELECT * FROM core.dim_products
ORDER BY product_id ASC
""", engine)

df_stores = pd.read_sql("""
SELECT * FROM core.dim_stores
ORDER BY store_id ASC
""", engine)


# -------------------------
# FACT TABLES
# -------------------------

df_sales = pd.read_sql("""
SELECT * FROM core.fact_sales
ORDER BY date ASC
""", engine)

df_inventory = pd.read_sql("""
SELECT * FROM core.fact_inventory
ORDER BY date ASC
""", engine)

df_customer_activity = pd.read_sql("""
SELECT * FROM core.fact_customer_activity
ORDER BY date ASC
""", engine)

df_store_operations = pd.read_sql("""
SELECT * FROM core.fact_store_operations
ORDER BY date ASC
""", engine)

df_promotions = pd.read_sql("""
SELECT * FROM core.fact_promotions
ORDER BY date ASC
""", engine)

df_restrictions = pd.read_sql("""
SELECT * FROM core.fact_restriction_events
ORDER BY date ASC
""", engine)

df_weather = pd.read_sql("""
SELECT * FROM core.fact_weather
ORDER BY date ASC
""", engine)

In [31]:
df_sales.head()

,date,store_id,product_id,units_sold,price,regular_price,discount_pct,promo_flag,promo_type,revenue,starting_inventory,restock_qty,ending_inventory,stockout_occurred,restriction_active,restriction_type,city,store_size,store_type,category
0,2021-01-01,1,1070,0,64012.0,64012,0,0,None,0.0,0,0,0,1,0,None,Benin,Large,Mall,Small Appliances
1,2021-01-01,1,1069,0,462942.0,462942,0,0,None,0.0,0,0,0,1,0,None,Benin,Large,Mall,Mobile Phones
2,2021-01-01,1,1068,6,338093.0,338093,0,0,None,2028558.0,11,0,5,0,0,None,Benin,Large,Mall,Mobile Phones
3,2021-01-01,1,1067,2,99634.0,99634,0,0,None,199268.0,7,0,5,0,0,None,Benin,Large,Mall,Network Devices
4,2021-01-01,1,1066,3,52233.0,52233,0,0,None,156699.0,4,0,1,0,0,None,Benin,Large,Mall,Small Appliances

In [53]:
df_sales.columns

Index(['date', 'store_id', 'product_id', 'units_sold', 'price',
       'regular_price', 'discount_pct', 'promo_flag', 'promo_type', 'revenue',
       'starting_inventory', 'restock_qty', 'ending_inventory',
       'stockout_occurred', 'restriction_active', 'restriction_type', 'city',
       'store_size', 'store_type', 'category'],
      dtype='object')

In [52]:
df_sales.store_type.unique()

array(['Mall', 'High Street', 'Plaza'], dtype=object)

In [32]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1618680 entries, 0 to 1618679
Data columns (total 20 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   date                1618680 non-null  object
 1   store_id            1618680 non-null  int64
 2   product_id          1618680 non-null  int64
 3   units_sold          1618680 non-null  int64
 4   price               1618680 non-null  float64
 5   regular_price       1618680 non-null  int64
 6   discount_pct        1618680 non-null  int64
 7   promo_flag          1618680 non-null  int64
 8   promo_type          225 non-null      object
 9   revenue             1618680 non-null  float64
 10  starting_inventory  1618680 non-null  int64
 11  restock_qty         1618680 non-null  int64
 12  ending_inventory    1618680 non-null  int64
 13  stockout_occurred   1618680 non-null  int64
 14  restriction_active  1618680 non-null  int64
 15  restriction_type    435478 non-null   object
 16  city                1618680 non-null  object
 17  store_size          1618680 non-null  object
 18  store_type          1618680 non-null  object
 19  category            1618680 non-null  object
dtypes: float64(2), int64(11), object(7)
memory usage: 247.0+ MB

In [34]:
df_products.shape

(120, 8)

In [36]:
df_policy_regimes

,policy_id,policy_name,start_date,end_date,affected_category,affected_store_type,demand_multiplier,discount_cap_pct,replenishment_multiplier,service_intensity_multiplier
0,1,Mall Expansion Drive,2021-04-10 00:00:00,2021-12-04 00:00:00,None,Mall,1.08,25,1.12,1.10
1,3,Small Store Inventory Control,2022-01-11 00:00:00,2022-07-21 00:00:00,None,Plaza,0.98,15,0.88,1.00
2,2,Small Store Inventory Control,2022-11-06,2023-05-19,None,Plaza,0.98,15,0.88,1.00
3,2,Telecom Seasonal Push,2024-11-09 00:00:00,2025-06-25 00:00:00,Telecom Services,None,1.15,20,1.10,1.08
4,1,Cooling Appliances Availability Programme,2024-11-19,2025-05-08,Air Conditioners,None,1.10,20,1.20,1.05
5,4,Cooling Appliances Availability Programme,2025-07-09 00:00:00,2025-10-20 00:00:00,Air Conditioners,None,1.10,20,1.20,1.05
6,3,Telecom Seasonal Push,2025-09-10,2026-04-06,Telecom Services,None,1.15,20,1.10,1.08
7,4,Premium Electronics Margin Protection,2025-09-30,2026-04-06,Mobile Phones,None,0.96,10,0.95,1.02
8,3,Cooling Appliances Availability Programme,2026-04-08 00:00:00,2026-04-11 00:00:00,Air Conditioners,None,1.10,20,1.20,1.05
9,1,Telecom Seasonal Push,2026-04-10 00:00:00,2026-04-11 00:00:00,Telecom Services,None,1.15,20,1.10,1.08
10,2,Premium Electronics Margin Protection,2026-04-10 00:00:00,2026-04-11 00:00:00,Mobile Phones,None,0.96,10,0.95,1.02
11,4,Mall Expansion Drive,2026-04-10 00:00:00,2026-04-11 00:00:00,None,Mall,1.08,25,1.12,1.10

In [43]:
print(df_sales.head())

         date  store_id  product_id  units_sold     price  regular_price  \
0  2021-01-01         1        1070           0   64012.0          64012
1  2021-01-01         1        1069           0  462942.0         462942
2  2021-01-01         1        1068           6  338093.0         338093
3  2021-01-01         1        1067           2   99634.0          99634
4  2021-01-01         1        1066           3   52233.0          52233

   discount_pct  promo_flag promo_type    revenue  starting_inventory  \
0             0           0       None        0.0                   0
1             0           0       None        0.0                   0
2             0           0       None  2028558.0                  11
3             0           0       None   199268.0                   7
4             0           0       None   156699.0                   4

   restock_qty  ending_inventory  stockout_occurred  restriction_active  \
0            0                 0                  1                   0
1            0                 0                  1                   0
2            0                 5                  0                   0
3            0                 5                  0                   0
4            0                 1                  0                   0

  restriction_type   city store_size store_type          category
0             None  Benin      Large       Mall  Small Appliances
1             None  Benin      Large       Mall     Mobile Phones
2             None  Benin      Large       Mall     Mobile Phones
3             None  Benin      Large       Mall   Network Devices
4             None  Benin      Large       Mall  Small Appliances

In [44]:
df['store_id'].nunique()

7

In [45]:
df['city'].nunique()

7

In [46]:
df['city'].unique()

array(['Benin', 'Ekpoma', 'Auchi', 'Irrua', 'Igueben', 'Agenebode',
       'Ogwa'], dtype=object)

In [47]:
df[['store_id', 'city']].drop_duplicates().sort_values('store_id')

     store_id       city
0           1      Benin
83          2     Ekpoma
240         3      Auchi
360         4      Irrua
480         5    Igueben
600         6  Agenebode
720         7       Ogwa

In [48]:
df_sales.product_id.nunique()

120

In [50]:
product_store_counts = (
    df.groupby('product_id')['store_id']
      .nunique()
      .reset_index(name='n_stores')
      .sort_values('n_stores', ascending=False)
)

print(product_store_counts.head(10))

    product_id  n_stores
0         1001         7
1         1002         7
88        1089         7
87        1088         7
86        1087         7
85        1086         7
84        1085         7
83        1084         7
82        1083         7
81        1082         7

In [51]:
df[df['product_id'] == 1069][['product_id', 'store_id', 'city', 'category']].drop_duplicates().sort_values(['product_id', 'store_id'])

     product_id  store_id       city       category
1          1069         1      Benin  Mobile Phones
188        1069         2     Ekpoma  Mobile Phones
308        1069         3      Auchi  Mobile Phones
428        1069         4      Irrua  Mobile Phones
548        1069         5    Igueben  Mobile Phones
668        1069         6  Agenebode  Mobile Phones
823        1069         7       Ogwa  Mobile Phones

In [54]:
df_sales.columns

Index(['date', 'store_id', 'product_id', 'units_sold', 'price',
       'regular_price', 'discount_pct', 'promo_flag', 'promo_type', 'revenue',
       'starting_inventory', 'restock_qty', 'ending_inventory',
       'stockout_occurred', 'restriction_active', 'restriction_type', 'city',
       'store_size', 'store_type', 'category'],
      dtype='object')

In [56]:
df_sales.discount_pct.value_counts()

discount_pct
0     1618678
15          2
Name: count, dtype: int64

In [58]:
print(df[['store_id', 'city', 'store_size']].drop_duplicates().sort_values('store_id'))

     store_id       city store_size
0           1      Benin      Large
83          2     Ekpoma     Medium
240         3      Auchi     Medium
360         4      Irrua      Small
480         5    Igueben      Small
600         6  Agenebode      Small
720         7       Ogwa      Small

In [59]:
df_stores.head()

,store_id,store_name,city,area,region,store_type,store_size
0,1,SunnyBest Benin Main,Benin,Oredo,Edo South,Mall,Large
1,2,SunnyBest Ekpoma,Ekpoma,Esan West,Edo Central,High Street,Medium
2,3,SunnyBest Auchi,Auchi,Etsako West,Edo North,High Street,Medium
3,4,SunnyBest Irrua,Irrua,Esan Central,Edo Central,Plaza,Small
4,5,SunnyBest Igueben,Igueben,Igueben,Edo Central,High Street,Small

In [63]:
df_stores

,store_id,store_name,city,area,region,store_type,store_size
0,1,SunnyBest Benin Main,Benin,Oredo,Edo South,Mall,Large
1,2,SunnyBest Ekpoma,Ekpoma,Esan West,Edo Central,High Street,Medium
2,3,SunnyBest Auchi,Auchi,Etsako West,Edo North,High Street,Medium
3,4,SunnyBest Irrua,Irrua,Esan Central,Edo Central,Plaza,Small
4,5,SunnyBest Igueben,Igueben,Igueben,Edo Central,High Street,Small
5,6,SunnyBest Agenebode,Agenebode,Etsako East,Edo North,Plaza,Small
6,7,SunnyBest Ogwa,Ogwa,Esan West,Edo Central,High Street,Small

In [65]:
print(df_policy_regimes)

    policy_id                                policy_name           start_date  \
0           1                       Mall Expansion Drive  2021-04-10 00:00:00
1           3              Small Store Inventory Control  2022-01-11 00:00:00
2           2              Small Store Inventory Control           2022-11-06
3           2                      Telecom Seasonal Push  2024-11-09 00:00:00
4           1  Cooling Appliances Availability Programme           2024-11-19
5           4  Cooling Appliances Availability Programme  2025-07-09 00:00:00
6           3                      Telecom Seasonal Push           2025-09-10
7           4      Premium Electronics Margin Protection           2025-09-30
8           3  Cooling Appliances Availability Programme  2026-04-08 00:00:00
9           1                      Telecom Seasonal Push  2026-04-10 00:00:00
10          2      Premium Electronics Margin Protection  2026-04-10 00:00:00
11          4                       Mall Expansion Drive  2026-04-10 00:00:00

               end_date affected_category affected_store_type  \
0   2021-12-04 00:00:00              None                Mall
1   2022-07-21 00:00:00              None               Plaza
2            2023-05-19              None               Plaza
3   2025-06-25 00:00:00  Telecom Services                None
4            2025-05-08  Air Conditioners                None
5   2025-10-20 00:00:00  Air Conditioners                None
6            2026-04-06  Telecom Services                None
7            2026-04-06     Mobile Phones                None
8   2026-04-11 00:00:00  Air Conditioners                None
9   2026-04-11 00:00:00  Telecom Services                None
10  2026-04-11 00:00:00     Mobile Phones                None
11  2026-04-11 00:00:00              None                Mall

    demand_multiplier  discount_cap_pct  replenishment_multiplier  \
0                1.08                25                      1.12
1                0.98                15                      0.88
2                0.98                15                      0.88
3                1.15                20                      1.10
4                1.10                20                      1.20
5                1.10                20                      1.20
6                1.15                20                      1.10
7                0.96                10                      0.95
8                1.10                20                      1.20
9                1.15                20                      1.10
10               0.96                10                      0.95
11               1.08                25                      1.12

    service_intensity_multiplier
0                           1.10
1                           1.00
2                           1.00
3                           1.08
4                           1.05
5                           1.05
6                           1.08
7                           1.02
8                           1.05
9                           1.08
10                          1.02
11                          1.10

In [69]:
df_products

,product_id,product_name,category,brand,regular_price,cost_price,is_seasonal,warranty_months
0,1001,LG Televisions Model-120,Televisions,LG,445838,332772,1,6
1,1002,Tecno Mobile Model-199,Mobile Phones,Tecno,500410,346208,1,6
2,1003,Tecno Mobile Model-905,Mobile Phones,Tecno,399365,244124,1,12
3,1004,Infinix Mobile Model-121,Mobile Phones,Infinix,305796,221242,1,12
4,1005,Samsung Mobile Model-781,Mobile Phones,Samsung,462752,326219,1,24
5,1006,Infinix Mobile Model-786,Mobile Phones,Infinix,193855,125337,1,12
6,1007,Century Small Model-584,Small Appliances,Century,16267,11687,0,24
7,1008,Binatone Small Model-415,Small Appliances,Binatone,75232,46117,0,6
8,1009,Hisense Air Model-439,Air Conditioners,Hisense,831912,501803,1,12
9,1010,Acer Laptops Model-134,Laptops & Computers,Acer,722843,505292,0,24
10,1011,Anker Accessories Model-489,Accessories,Anker,8943,6716,0,12
11,1012,Acer Laptops Model-829,Laptops & Computers,Acer,321829,195112,0,12
12,1013,Samsung Televisions Model-915,Televisions,Samsung,303165,238085,1,24
13,1014,Acer Laptops Model-819,Laptops & Computers,Acer,413160,327319,0,6
14,1015,Century Small Model-863,Small Appliances,Century,24268,17408,0,6
15,1016,Binatone Small Model-164,Small Appliances,Binatone,54976,36243,0,6
16,1017,Samsung Mobile Model-238,Mobile Phones,Samsung,190151,129108,1,24
17,1018,Tecno Mobile Model-589,Mobile Phones,Tecno,131858,99454,1,6
18,1019,LG Televisions Model-132,Televisions,LG,364806,280903,1,12
19,1020,Itel Mobile Model-646,Mobile Phones,Itel,547867,398579,1,24
20,1021,LG Refrigerators Model-104,Refrigerators,LG,239182,177628,1,6
21,1022,Panasonic Air Model-114,Air Conditioners,Panasonic,715270,434946,1,24
22,1023,Infinix Mobile Model-340,Mobile Phones,Infinix,513852,329041,1,24
23,1024,Acer Laptops Model-848,Laptops & Computers,Acer,561357,352457,0,24
24,1025,LG Air Model-798,Air Conditioners,LG,264899,208891,1,24
25,1026,Philips Small Model-745,Small Appliances,Philips,58689,44698,0,6
26,1027,Hisense Refrigerators Model-447,Refrigerators,Hisense,252906,168149,1,24
27,1028,Samsung Televisions Model-844,Televisions,Samsung,534589,320809,1,6
28,1029,Lenovo Laptops Model-926,Laptops & Computers,Lenovo,378576,236221,0,24
29,1030,HP Laptops Model-541,Laptops & Computers,HP,268451,180593,0,6
30,1031,Glo Telecom Model-724,Telecom Services,Glo,12149,9020,1,6
31,1032,Airtel Telecom Model-835,Telecom Services,Airtel,5237,3572,1,24
32,1033,Generic Accessories Model-515,Accessories,Generic,26556,18533,0,12
33,1034,Panasonic Air Model-866,Air Conditioners,Panasonic,722794,487113,1,6
34,1035,Huawei Network Model-610,Network Devices,Huawei,72083,57427,0,12
35,1036,Samsung Mobile Model-563,Mobile Phones,Samsung,425528,282616,1,12
36,1037,Infinix Mobile Model-445,Mobile Phones,Infinix,203883,149958,1,24
37,1038,Haier Thermocool Refrigerators Model-739,Refrigerators,Haier Thermocool,242483,176778,1,6
38,1039,LG Refrigerators Model-250,Refrigerators,LG,757162,505945,1,6
39,1040,Hisense Air Model-723,Air Conditioners,Hisense,654594,422677,1,12
40,1041,LG Air Model-751,Air Conditioners,LG,757409,605359,1,12
41,1042,Panasonic Air Model-915,Air Conditioners,Panasonic,798376,523554,1,24
42,1043,ZTE Network Model-724,Network Devices,ZTE,79040,57573,0,24
43,1044,Infinix Mobile Model-198,Mobile Phones,Infinix,249426,168227,1,6
44,1045,Glo Telecom Model-921,Telecom Services,Glo,14707,9722,1,12
45,1046,LG Televisions Model-497,Televisions,LG,698467,518566,1,6
46,1047,Acer Laptops Model-294,Laptops & Computers,Acer,208871,152460,0,24
47,1048,Binatone Small Model-569,Small Appliances,Binatone,75079,46454,0,24
48,1049,Asus Laptops Model-126,Laptops & Computers,Asus,879650,684727,0,24
49,1050,ZTE Network Model-552,Network Devices,ZTE,117888,84334,0,6
50,1051,Lenovo Laptops Model-271,Laptops & Computers,Lenovo,777234,585809,0,6
51,1052,Oraimo Accessories Model-991,Accessories,Oraimo,22453,17580,0,24
52,1053,Itel Mobile Model-198,Mobile Phones,Itel,428896,304753,1,24
53,1054,9mobile Telecom Model-260,Telecom Services,9mobile,690,456,1,24
54,1055,Dell Laptops Model-669,Laptops & Computers,Dell,839944,570270,0,12
55,1056,Anker Accessories Model-738,Accessories,Anker,12455,9144,0,24
56,1057,Hisense Refrigerators Model-492,Refrigerators,Hisense,276089,206557,1,6
57,1058,Century Small Model-966,Small Appliances,Century,69748,45984,0,12
58,1059,Asus Laptops Model-135,Laptops & Computers,Asus,369963,259813,0,6
59,1060,Huawei Network Model-982,Network Devices,Huawei,97575,72243,0,12
60,1061,Acer Laptops Model-953,Laptops & Computers,Acer,182097,112680,0,24
61,1062,Dell Laptops Model-413,Laptops & Computers,Dell,855086,680963,0,12
62,1063,Oraimo Accessories Model-543,Accessories,Oraimo,9777,7474,0,12
63,1064,Asus Laptops Model-202,Laptops & Computers,Asus,401451,258198,0,6
64,1065,Itel Mobile Model-966,Mobile Phones,Itel,259407,183211,1,24
65,1066,Binatone Small Model-758,Small Appliances,Binatone,52233,36733,0,12
66,1067,TP-Link Network Model-445,Network Devices,TP-Link,99634,68527,0,24
67,1068,Itel Mobile Model-740,Mobile Phones,Itel,338093,259383,1,6
68,1069,Samsung Mobile Model-217,Mobile Phones,Samsung,462942,300934,1,12
69,1070,Binatone Small Model-803,Small Appliances,Binatone,64012,46578,0,6
70,1071,Hisense Air Model-755,Air Conditioners,Hisense,352764,241262,1,12
71,1072,Samsung Mobile Model-146,Mobile Phones,Samsung,425612,265247,1,6
72,1073,Infinix Mobile Model-573,Mobile Phones,Infinix,230196,159948,1,12
73,1074,Haier Thermocool Refrigerators Model-456,Refrigerators,Haier Thermocool,584963,371241,1,12
74,1075,Samsung Televisions Model-861,Televisions,Samsung,440260,342229,1,24
75,1076,Oraimo Accessories Model-357,Accessories,Oraimo,14540,10712,0,24
76,1077,Tecno Mobile Model-774,Mobile Phones,Tecno,267459,191258,1,12
77,1078,Binatone Small Model-367,Small Appliances,Binatone,20052,14219,0,6
78,1079,LG Televisions Model-496,Televisions,LG,584999,456925,1,6
79,1080,Dell Laptops Model-826,Laptops & Computers,Dell,771820,477670,0,24
80,1081,Itel Mobile Model-517,Mobile Phones,Itel,184585,135914,1,12
81,1082,Acer Laptops Model-174,Laptops & Computers,Acer,232745,172079,0,6
82,1083,Oraimo Accessories Model-968,Accessories,Oraimo,28548,18739,0,12
83,1084,TP-Link Network Model-195,Network Devices,TP-Link,103042,70328,0,12
84,1085,Asus Laptops Model-378,Laptops & Computers,Asus,456955,313379,0,6
85,1086,Huawei Network Model-695,Network Devices,Huawei,75069,58592,0,12
86,1087,ZTE Network Model-332,Network Devices,ZTE,86234,53464,0,6
87,1088,Huawei Network Model-483,Network Devices,Huawei,55270,43738,0,24
88,1089,Hisense Refrigerators Model-198,Refrigerators,Hisense,105486,65048,1,6
89,1090,Century Small Model-243,Small Appliances,Century,36972,27746,0,24
90,1091,Huawei Network Model-497,Network Devices,Huawei,109780,76723,0,24
91,1092,LG Air Model-757,Air Conditioners,LG,138102,97939,1,24
92,1093,MTN Telecom Model-329,Telecom Services,MTN,17837,12907,1,6
93,1094,Itel Mobile Model-894,Mobile Phones,Itel,251415,154507,1,12
94,1095,Binatone Small Model-747,Small Appliances,Binatone,37556,23170,0,24
95,1096,LG Televisions Model-316,Televisions,LG,318067,205896,1,24
96,1097,Hisense Air Model-975,Air Conditioners,Hisense,844699,520925,1,6
97,1098,Panasonic Air Model-550,Air Conditioners,Panasonic,548345,365225,1,12
98,1099,Dell Laptops Model-994,Laptops & Computers,Dell,814795,582003,0,6
99,1100,Binatone Small Model-604,Small Appliances,Binatone,54298,38913,0,12
100,1101,LG Televisions Model-216,Televisions,LG,628248,486087,1,12
101,1102,9mobile Telecom Model-914,Telecom Services,9mobile,13472,10696,1,6
102,1103,Anker Accessories Model-775,Accessories,Anker,32860,26241,0,6
103,1104,LG Air Model-625,Air Conditioners,LG,738353,467556,1,6
104,1105,HP Laptops Model-755,Laptops & Computers,HP,651108,481419,0,24
105,1106,Century Small Model-507,Small Appliances,Century,28323,22424,0,12
106,1107,Philips Small Model-415,Small Appliances,Philips,61427,44802,0,12
107,1108,LG Air Model-601,Air Conditioners,LG,227016,148012,1,24
108,1109,Samsung Mobile Model-831,Mobile Phones,Samsung,410896,280330,1,6
109,1110,Asus Laptops Model-693,Laptops & Computers,Asus,315421,194059,0,12
110,1111,LG Televisions Model-923,Televisions,LG,655278,513630,1,12
111,1112,Generic Accessories Model-473,Accessories,Generic,34548,21867,0,6
112,1113,TP-Link Network Model-953,Network Devices,TP-Link,82292,61712,0,6
113,1114,Huawei Network Model-198,Network Devices,Huawei,66540,40769,0,6
114,1115,Itel Mobile Model-808,Mobile Phones,Itel,504159,310093,1,6
115,1116,Glo Telecom Model-664,Telecom Services,Glo,15606,11097,1,6
116,1117,Anker Accessories Model-977,Accessories,Anker,18456,11963,0,6
117,1118,Asus Laptops Model-447,Laptops & Computers,Asus,696237,540032,0,12
118,1119,Dell Laptops Model-870,Laptops & Computers,Dell,658153,463380,0,12
119,1120,LG Refrigerators Model-833,Refrigerators,LG,740053,587302,1,12